she_codes_news/news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.StoryView.as_view(), name='story'),
    path('add-story/', views.AddStoryView.as_view(), name='newStory')
]

she_codes_news/she_codes_news/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('news/', include('news.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls'))
]

# http://localhost:8000/users/login
# http://localhost:8000/users/logout

she_codes_news/users/urls.py
from django.urls import path
from .views import CreateAccountView
from .views import ChangeAccountView

app_name = 'users'

urlpatterns = [
    path('create-account/', CreateAccountView.as_view(), name='createAccount'),
    path('<int:pk>/', ChangeAccountView.as_view(), name='changeAccount')

]


    # path('<int:pk>/', views.StoryView.as_view(), name='story'),

she_codes_news/news/models.py
from django.db import models
from django.contrib.auth import get_user_model


class NewsStory(models.Model):
    title = models.CharField(max_length=200)
    # author = models.CharField(max_length=200)
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE
        # ^ if we delete the user, it will also delete their stories
    )
    pub_date = models.DateTimeField()
    content = models.TextField()
    image = models.TextField(default="https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/golden-retriever-royalty-free-image-506756303-1560962726.jpg")
    
    @property
    def ret_image(self):
        if self.image.startswith("http"):
            return self.image
        return "https://picsum.photos/600"

she_codes_news/users/models.py
from django.db import models

# # Create your models here.

from django.contrib.auth.models import AbstractUser
from django.contrib.auth import get_user_model
from django.db import models

class CustomUser(AbstractUser):
    # this is where i would put custom fields, e.g. profile picture
    # pass
    first_name = models.TextField(max_length=30, blank=True)
    last_name = models.TextField(max_length=30, blank=True)
    location = models.TextField(max_length=30, blank=True)
    about_me = models.TextField(max_length=500, blank=True)
    favourite_dog_breed = models.TextField(max_length=50, blank=True)
    favourite_cupcake_flavour = models.TextField(max_length=50, blank=True)
    # profile_picture = models.ImageField(blank=True)

    def __str__(self):
        # return f'{self.username} Profile'
        return self.username

she_codes_news/news/forms.py
from django import forms
from django.forms import ModelForm
from .models import NewsStory



class StoryForm(ModelForm):
    class Meta:
        model = NewsStory
        fields = ['title', 'pub_date', 'content', 'image']
        widgets = {
            'pub_date': forms.DateInput(format=('%m/%d/%Y'),
            attrs={'class':'form-control', 'placeholder':'Select a date',
            'type':'date'}),
        }

she_codes_news/users/forms.py
from django import forms
from django.contrib.auth.forms import (
    UserCreationForm,
    UserChangeForm
)

from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ['username', 'email']


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ['username', 'first_name', 'last_name', 'email', 'location', 'about_me', 'favourite_dog_breed', 'favourite_cupcake_flavour']

she_codes_news/news/views.py
from django.views import generic
from django.urls import reverse_lazy
from .models import NewsStory
from .forms import StoryForm


class IndexView(generic.ListView):
    template_name = 'news/index.html'

    def get_queryset(self):
        '''Return all news stories.'''
        # return NewsStory.objects.all()
        return NewsStory.objects.order_by('-pub_date')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context['latest_stories'] = NewsStory.objects.all()[:4]
        # context['all_stories'] = NewsStory.objects.all()
        context['latest_stories'] = NewsStory.objects.order_by('-pub_date')[:4]
        context['all_stories'] = NewsStory.objects.order_by('-pub_date')
        return context

class StoryView(generic.DetailView):
    model = NewsStory
    template_name = 'news/story.html'
    context_object_name = 'story'

class AddStoryView(generic.CreateView):
    form_class = StoryForm
    context_object_name = 'storyForm'
    template_name = 'news/createStory.html'
    success_url = reverse_lazy('news:index')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

she_codes_news/users/views.py
# from django.shortcuts import render

# # Create your views here.
from django.urls import reverse_lazy
from django.views import generic
from django.views.generic.edit import CreateView
from django.views.generic.edit import UpdateView
from .models import CustomUser
from .forms import CustomUserCreationForm
from .forms import CustomUserChangeForm

class CreateAccountView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'users/createAccount.html'

class ChangeAccountView(UpdateView):
    model = CustomUser
    form_class = CustomUserChangeForm
    # success_url = reverse_lazy('news:index')
    template_name = 'users/changeAccount.html'

    def get_success_url(self):
        userid = self.kwargs['pk']
        return reverse_lazy('users:changeAccount', kwargs={'pk': userid})

she_codes_news/news/templates/news/createStory.html
{% extends "base.html" %}

{% block content %}

<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="submit">
</form>

{% endblock %}

she_codes_news/news/templates/news/index.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
<!-- <a href="{% url 'news:newStory' %}">Write New Story</a> -->
{% endblock%}

{% block content %}

 <h2>Latest News</h2>

    <div id="latest-stories">
        {% if latest_stories %}
            {% for story in latest_stories %}
                {% include "./storyCard.html" with story=story position=forloop.counter %}
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>

    <div id="all-stories">
        {% if latest_stories %}
            {% for story in all_stories %}
                {% include "./storyCard.html" with story=story %}
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>

{% endblock %}

she_codes_news/news/templates/news/story.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}

<div id="story-wrapper">
    <h2>{{ story.title }}</h2>
    <h4>{{ story.author }}</h4>
    <div id="story-content">
        <!-- <img src="{% static '/news/images/placeholder-5.jpg' %}"> -->
        <img src="{{ story.image }}">
        {{ story.content|linebreaks }}
    </div>
</div>

{% endblock %}

she_codes_news/news/templates/news/storyCard.html
<div class="story-card" id="story-card-{{ position }}">
    <a href="{% url 'news:story' story.id %}">
        <img src={{ story.ret_image }}>
        <div class="story-card-text">
            <h3>{{ story.title }}</h3>
            <h4>{{ story.author }}</h4>
            <h4>{{ story.pub_date }}</h4>
        </div>
    </a>
</div>

she_codes_news/templates/base.html
{% load static %}

<!doctype html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>She Codes News</title>
        <meta name="description" content="">
        <meta name="author" content="Rebecca Millwood">
        <link href="https://fonts.googleapis.com/css?family=Manjari&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
        {% block stylesheets %}{% endblock %}
    </head>

    <body>
        <header>
            <div id="header-text">
                <a id="header-link" href="{% url 'news:index' %}">
                    <h1><span style="color:#8246AF;">She </span><span style="color:#FDA103;">{Codes}</span><span style="color:#8246AF;"> News</span></h1>
                </a>
            </div>
            <!-- include nav here -->
            {% include './nav.html' %}
        </header>

        <!-- content blocks here -->
        {% block content %}{% endblock%}
        
    </body>
</html>

she_codes_news/templates/nav.html
<nav>
    <a href="{% url 'news:index' %}">Home</a>
    {% if request.user.is_authenticated %}
        <a href="{% url 'users:changeAccount' user.id %}">{{ user.username }}'s Account</a>
        <a href="{% url 'news:newStory' %}">Write New Story</a>
        <a href="{% url 'logout' %}">Logout</a>
    {% else %}
        <a href="{% url 'login' %}">Login</a>
        <a href="{% url 'users:createAccount' %}">Create Account</a>
    {% endif %}  
</nav>

she_codes_news/users/templates/users/changeAccount.html
{% extends 'base.html' %}

{% block content %}
<h2>Welcome To Your Account!</h2>
<h3>Hey {{ user.username }}, it's lovely to see you!</h3>
<h4>Use the fields below if you'd like to update your account details:</h4>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Update My Account!</button>
</form>
{% endblock %}

she_codes_news/users/templates/users/createAccount.html
{% extends 'base.html' %}

{% block content %}
<h2>Create An Account</h2>
<h3>Creating a She {Codes} News account allows <br> you to contribute to our growing news story site, <br> and we'd love to have you!</h3>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Create My Account!</button>
<h4>Forgot you already have an account? <a href="{% url 'login' %}"><span style="color:#8246AF;">No worries, log back in here!</span></a> </h4> 
</form>
{% endblock %}